---
 databaseConfig:
      user : "ENTER_USER_HERE"
      host : "ENTER_HOST_HERE" # use 'host.docker.internal' in case of connecting to a local database
      database: "ENTER_DB_NAME_HERE"
      password  : "ENTER_PASSWORD_HERE"
      port: "ENTER_PORT_HERE"
      
 gasTanks:
   - name: "ENTER_GASTANK_NAME_HERE"
     apiKey: "ENTER_BICONOMY_API_KEY_HERE"
     chainId: "ENTER_CHAIN_ID_HERE"
     providerURL: "ENTER_PROVIDER_URL_HERE"
     whiteList:  
        - "ENTER_CONTRACT_ADDRESS_1_HERE"
        - "ENTER_CONTRACT_ADDRESS_2_HERE"