version: "3.8"


services:
    nodeserver:
        build:
            context: ./server
        # ports:
        #     - "3000:3000"
        network_mode: "host"
    
    nginx:
        restart: always
        build:
            context: ./nginx
        # ports:
        #     - "80:80"
        #     - "443:443"
        network_mode: "host"
